// ═══════════════════════════════════════════════════════════════
//  LE PENDU MÉDECINE · words.js
//  Dictionnaire médical enrichi — format { word, definition, category }
//  Source : assets/dico/mots_v2.json (chargé dynamiquement si présent)
//  Fallback : tableau WORDS_DATA intégré ci-dessous
// ═══════════════════════════════════════════════════════════════

const WORDS_DATA = [
  // ── ANATOMIE ─────────────────────────────────────────────────
  { word: "abdomen",       definition: "Partie du corps comprise entre la poitrine et le bassin",                        category: "Anatomie" },
  { word: "articulation",  definition: "Point de contact mobile entre deux os",                                          category: "Anatomie" },
  { word: "cerveau",       definition: "Organe principal du système nerveux central situé dans le crâne",                category: "Anatomie" },
  { word: "coeur",         definition: "Organe musculaire creux qui propulse le sang dans les vaisseaux",                category: "Anatomie" },
  { word: "colonne vertebrale", definition: "Série de vertèbres empilées formant l'axe du squelette dorsal",            category: "Anatomie" },
  { word: "epaule",        definition: "Jointure reliant le bras au tronc, la plus mobile du corps humain",             category: "Anatomie" },
  { word: "foie",          definition: "Glande abdominale volumineuse impliquée dans la digestion et la détoxification", category: "Anatomie" },
  { word: "intestin",      definition: "Organe tubulaire de la digestion situé entre l'estomac et l'anus",              category: "Anatomie" },
  { word: "jambes",        definition: "Segments inférieurs des membres inférieurs reliant la cuisse au pied",          category: "Anatomie" },
  { word: "larynx",        definition: "Organe creux de la phonation situé dans la gorge contenant les cordes vocales", category: "Anatomie" },
  { word: "poumon",        definition: "Organe pair de la respiration occupant la majeure partie de la cage thoracique", category: "Anatomie" },
  { word: "reins",         definition: "Organes pairs filtrant le sang pour éliminer les déchets dans l'urine",         category: "Anatomie" },
  { word: "retine",        definition: "Membrane sensible à la lumière tapissant le fond de l'œil",                     category: "Anatomie" },
  { word: "trachee",       definition: "Conduit cartilagineux reliant le larynx aux bronches",                           category: "Anatomie" },
  { word: "vertèbre",      definition: "Os de la colonne vertébrale assurant la protection de la moelle épinière",      category: "Anatomie" },
  { word: "aorte",         definition: "Plus grande artère du corps partant directement du ventricule gauche",          category: "Anatomie" },
  { word: "diaphragme",    definition: "Muscle en dôme séparant la cage thoracique de l'abdomen, principal muscle respiratoire", category: "Anatomie" },
  { word: "duodenum",      definition: "Première partie de l'intestin grêle faisant suite à l'estomac",                 category: "Anatomie" },
  { word: "estomac",       definition: "Organe musculaire creux de la digestion situé entre l'œsophage et l'intestin", category: "Anatomie" },
  { word: "hypothalamus",  definition: "Région du cerveau régulant les fonctions vitales comme la température et la faim", category: "Anatomie" },
  { word: "moelle epiniere",definition: "Cordon nerveux reliant le cerveau aux nerfs périphériques à l'intérieur de la colonne", category: "Anatomie" },
  { word: "pancreas",      definition: "Glande mixte sécrétant des sucs digestifs et l'insuline",                       category: "Anatomie" },
  { word: "rate",          definition: "Organe lymphoïde filtrant le sang et participant à l'immunité",                 category: "Anatomie" },
  { word: "thyroide",      definition: "Glande endocrine située dans le cou produisant des hormones régulant le métabolisme", category: "Anatomie" },
  { word: "uretre",        definition: "Canal excréteur de l'urine depuis la vessie vers l'extérieur",                  category: "Anatomie" },
  { word: "uterus",        definition: "Organe musculaire creux de la femme où se développe l'embryon",                 category: "Anatomie" },
  { word: "vessie",        definition: "Réservoir musculaire stockant l'urine avant la miction",                        category: "Anatomie" },
  { word: "cornee",        definition: "Tissu transparent recouvrant la partie antérieure de l'œil",                    category: "Anatomie" },
  { word: "hippocampe",    definition: "Structure cérébrale essentielle à la mémoire et à l'orientation spatiale",      category: "Anatomie" },
  { word: "glande surrenale",definition: "Glande endocrine surmontant chaque rein, productrice d'adrénaline",          category: "Anatomie" },

  // ── PATHOLOGIES ──────────────────────────────────────────────
  { word: "allergie",      definition: "Réaction exagérée du système immunitaire à une substance étrangère inoffensive", category: "Pathologie" },
  { word: "appendicite",   definition: "Inflammation aiguë de l'appendice vermiculaire nécessitant souvent une chirurgie", category: "Pathologie" },
  { word: "arthrose",      definition: "Dégénérescence du cartilage articulaire responsable de douleurs chroniques",    category: "Pathologie" },
  { word: "bronchite",     definition: "Inflammation aiguë ou chronique de la muqueuse des bronches",                   category: "Pathologie" },
  { word: "cataracte",     definition: "Opacification progressive du cristallin de l'œil entraînant une baisse de vision", category: "Pathologie" },
  { word: "cancer",        definition: "Prolifération incontrôlée de cellules anormales pouvant envahir les tissus voisins", category: "Pathologie" },
  { word: "cystite",       definition: "Infection bactérienne de la muqueuse de la vessie, plus fréquente chez la femme", category: "Pathologie" },
  { word: "diabete",       definition: "Trouble métabolique caractérisé par une hyperglycémie chronique",               category: "Pathologie" },
  { word: "diarrhee",      definition: "Émission fréquente de selles liquides ou molles, souvent d'origine infectieuse", category: "Pathologie" },
  { word: "embolie pulmonaire", definition: "Obstruction d'une artère pulmonaire par un caillot sanguin migrant",      category: "Pathologie" },
  { word: "epilepsie",     definition: "Trouble neurologique caractérisé par des décharges électriques cérébrales anormales", category: "Pathologie" },
  { word: "fibromyalgie",  definition: "Syndrome douloureux chronique diffus accompagné de fatigue intense",            category: "Pathologie" },
  { word: "grippe",        definition: "Infection virale respiratoire aiguë causée par les virus Influenza",             category: "Pathologie" },
  { word: "hernie",        definition: "Sortie d'un organe hors de sa cavité naturelle à travers un orifice",           category: "Pathologie" },
  { word: "hypertension",  definition: "Élévation persistante de la pression artérielle au-dessus des valeurs normales", category: "Pathologie" },
  { word: "hypotension",   definition: "Diminution de la pression artérielle pouvant provoquer vertiges et syncopes",   category: "Pathologie" },
  { word: "insomnie",      definition: "Trouble du sommeil caractérisé par une difficulté à s'endormir ou à rester endormi", category: "Pathologie" },
  { word: "lombalgie",     definition: "Douleur dans la région lombaire de la colonne vertébrale, le mal de dos",       category: "Pathologie" },
  { word: "melanome",      definition: "Cancer cutané développé à partir des mélanocytes, souvent lié aux UV",          category: "Pathologie" },
  { word: "migraine",      definition: "Céphalée unilatérale intense souvent accompagnée de nausées et de photophobie", category: "Pathologie" },
  { word: "nephrite",      definition: "Inflammation du tissu rénal pouvant aboutir à une insuffisance rénale",         category: "Pathologie" },
  { word: "nevralgie",     definition: "Douleur vive suivant le trajet d'un nerf, souvent de type électrique",          category: "Pathologie" },
  { word: "obesite",       definition: "Excès de masse grasse défini par un IMC supérieur à 30, facteur de risque cardiovasculaire", category: "Pathologie" },
  { word: "pandemie",      definition: "Épidémie d'une maladie qui se répand à l'échelle mondiale",                     category: "Pathologie" },
  { word: "phlebite",      definition: "Formation d'un caillot obstruant une veine, le plus souvent dans les jambes",   category: "Pathologie" },
  { word: "pneumonie",     definition: "Infection aiguë du parenchyme pulmonaire causée par bactéries, virus ou champignons", category: "Pathologie" },
  { word: "psoriasis",     definition: "Maladie inflammatoire chronique de la peau formant des plaques rouges squameuses", category: "Pathologie" },
  { word: "septicemie",    definition: "Infection bactérienne grave du sang menaçant le pronostic vital",               category: "Pathologie" },
  { word: "sida",          definition: "Syndrome d'immunodéficience acquise causé par le VIH détruisant les lymphocytes CD4", category: "Pathologie" },
  { word: "tachycardie",   definition: "Accélération du rythme cardiaque au-delà de 100 battements par minute au repos", category: "Pathologie" },
  { word: "thrombose",     definition: "Formation d'un caillot dans un vaisseau sanguin obstruant la circulation",      category: "Pathologie" },
  { word: "tuberculose",   definition: "Infection bactérienne chronique des poumons causée par Mycobacterium tuberculosis", category: "Pathologie" },
  { word: "ulcere",        definition: "Perte de substance d'un tissu de revêtement formant une plaie ouverte",         category: "Pathologie" },
  { word: "varicelle",     definition: "Maladie infectieuse virale très contagieuse causée par le virus varicelle-zona", category: "Pathologie" },
  { word: "gastrite",      definition: "Inflammation de la muqueuse de l'estomac pouvant provoquer des douleurs épigastriques", category: "Pathologie" },
  { word: "glaucome",      definition: "Maladie oculaire caractérisée par une pression intraoculaire élevée lésant le nerf optique", category: "Pathologie" },
  { word: "leucemie",      definition: "Cancer des cellules souches hématopoïétiques entraînant une prolifération anormale de globules blancs", category: "Pathologie" },
  { word: "sclerose en plaques", definition: "Maladie inflammatoire démyélinisante du système nerveux central d'origine auto-immune", category: "Pathologie" },
  { word: "parkinson",     definition: "Maladie neurodégénérative chronique affectant le mouvement par destruction des neurones dopaminergiques", category: "Pathologie" },
  { word: "alzheimer",     definition: "Maladie neurodégénérative progressive caractérisée par des pertes de mémoire et un déclin cognitif", category: "Pathologie" },
  { word: "infarctus",     definition: "Nécrose d'un tissu consécutive à l'obstruction de son artère nourricière, surtout au myocarde", category: "Pathologie" },
  { word: "aneurisme",     definition: "Dilatation localisée et anormale de la paroi d'un vaisseau sanguin pouvant se rompre", category: "Pathologie" },
  { word: "cirrhose",      definition: "Fibrose avancée du foie consécutive à des lésions chroniques, souvent alcoolique", category: "Pathologie" },
  { word: "endometriose",  definition: "Présence de tissu endométrial en dehors de l'utérus causant douleurs et infertilité", category: "Pathologie" },
  { word: "spondylarthrite ankylosante", definition: "Maladie inflammatoire chronique touchant principalement les articulations de la colonne vertébrale", category: "Pathologie" },
  { word: "polyarthrite rhumatoide",     definition: "Rhumatisme inflammatoire chronique auto-immun détruisant progressivement les articulations", category: "Pathologie" },

  // ── PHARMACOLOGIE & TRAITEMENTS ──────────────────────────────
  { word: "antibiotique",  definition: "Médicament détruisant ou inhibant la croissance des bactéries",                 category: "Pharmacologie" },
  { word: "antiviral",     definition: "Médicament agissant spécifiquement contre les infections virales",               category: "Pharmacologie" },
  { word: "anesthesie",    definition: "Suppression temporaire de la sensibilité à la douleur lors d'une intervention", category: "Pharmacologie" },
  { word: "chimiotherapie",definition: "Traitement médicamenteux des cancers par des agents cytotoxiques",               category: "Pharmacologie" },
  { word: "corticoide",    definition: "Hormone stéroïde ou dérivé synthétique aux puissantes propriétés anti-inflammatoires", category: "Pharmacologie" },
  { word: "defibrillateur",definition: "Appareil délivrant un choc électrique pour restaurer un rythme cardiaque normal", category: "Pharmacologie" },
  { word: "dialyse",       definition: "Épuration extrarénale du sang par filtration à travers une membrane semi-perméable", category: "Pharmacologie" },
  { word: "diuretique",    definition: "Médicament augmentant la production d'urine pour éliminer l'excès de sel et d'eau", category: "Pharmacologie" },
  { word: "inhalateur",    definition: "Dispositif permettant l'administration de médicaments sous forme d'aérosol dans les voies respiratoires", category: "Pharmacologie" },
  { word: "insuline",      definition: "Hormone pancréatique régulant la glycémie en facilitant l'entrée du glucose dans les cellules", category: "Pharmacologie" },
  { word: "morphine",      definition: "Analgésique opioïde puissant utilisé dans le traitement des douleurs intenses",  category: "Pharmacologie" },
  { word: "phytotherapie", definition: "Utilisation thérapeutique de plantes médicinales ou de leurs extraits",          category: "Pharmacologie" },
  { word: "probiotiques",  definition: "Micro-organismes vivants bénéfiques pour l'équilibre de la flore intestinale",  category: "Pharmacologie" },
  { word: "radiotherapie", definition: "Traitement des tumeurs par irradiation ciblée avec des rayonnements ionisants",  category: "Pharmacologie" },
  { word: "sedatif",       definition: "Médicament déprimant le système nerveux central induisant calme ou sommeil",     category: "Pharmacologie" },
  { word: "vaccin",        definition: "Préparation antigénique stimulant l'immunité acquise contre une maladie spécifique", category: "Pharmacologie" },
  { word: "vaccination",   definition: "Administration de vaccins pour prévenir des maladies infectieuses",              category: "Pharmacologie" },
  { word: "anticoagulant", definition: "Médicament réduisant la coagulation du sang et prévenant la formation de caillots", category: "Pharmacologie" },
  { word: "antidepresseur",definition: "Médicament psychotrope utilisé pour traiter les états dépressifs et certains troubles anxieux", category: "Pharmacologie" },
  { word: "beta bloquant", definition: "Médicament bloquant les effets de l'adrénaline sur le cœur ralentissant le rythme cardiaque", category: "Pharmacologie" },

  // ── BIOLOGIE & PHYSIOLOGIE ───────────────────────────────────
  { word: "anatomie",      definition: "Science étudiant la structure morphologique et l'organisation du corps humain",  category: "Biologie" },
  { word: "antigene",      definition: "Molécule étrangère déclenchant une réponse immunitaire spécifique dans l'organisme", category: "Biologie" },
  { word: "antioxydant",   definition: "Molécule neutralisant les radicaux libres et protégeant les cellules du stress oxydatif", category: "Biologie" },
  { word: "bacterie",      definition: "Micro-organisme procaryote unicellulaire présent dans tous les environnements",  category: "Biologie" },
  { word: "cellule",       definition: "Unité structurale et fonctionnelle fondamentale de tout organisme vivant",       category: "Biologie" },
  { word: "chromosome",    definition: "Structure filamentaire portant l'ADN dans le noyau cellulaire",                  category: "Biologie" },
  { word: "coagulation",   definition: "Processus de solidification du sang par formation d'un réseau de fibrine",      category: "Biologie" },
  { word: "enzyme",        definition: "Protéine catalyseur accélérant les réactions biochimiques de l'organisme",      category: "Biologie" },
  { word: "genetique",     definition: "Science étudiant les gènes, l'hérédité et la variation des organismes",         category: "Biologie" },
  { word: "hemoglobine",   definition: "Protéine des globules rouges transportant l'oxygène des poumons aux tissus",    category: "Biologie" },
  { word: "hormone",       definition: "Molécule messager produite par une glande endocrine régulant des fonctions à distance", category: "Biologie" },
  { word: "immunite",      definition: "Capacité de l'organisme à se défendre contre les agents pathogènes",            category: "Biologie" },
  { word: "leucocytes",    definition: "Globules blancs du sang jouant le rôle principal dans les défenses immunitaires", category: "Biologie" },
  { word: "lymphocyte",    definition: "Type de leucocyte impliqué dans la réponse immunitaire adaptative",              category: "Biologie" },
  { word: "metabolisme",   definition: "Ensemble des réactions chimiques maintenant les fonctions vitales de l'organisme", category: "Biologie" },
  { word: "microbiome",    definition: "Ensemble des micro-organismes peuplant un écosystème, notamment l'intestin",    category: "Biologie" },
  { word: "mitose",        definition: "Division cellulaire produisant deux cellules filles génétiquement identiques",   category: "Biologie" },
  { word: "neurone",       definition: "Cellule nerveuse transmettant l'influx nerveux via ses prolongements",           category: "Biologie" },
  { word: "pathologie",    definition: "Discipline médicale étudiant les maladies, leurs causes et leurs mécanismes",   category: "Biologie" },
  { word: "plasma",        definition: "Partie liquide du sang dans laquelle baignent les éléments figurés",             category: "Biologie" },
  { word: "plaquettes",    definition: "Éléments figurés du sang jouant un rôle essentiel dans la coagulation",         category: "Biologie" },
  { word: "respiration",   definition: "Processus d'échanges gazeux entre l'organisme et son milieu",                   category: "Biologie" },
  { word: "serum",         definition: "Plasma sanguin débarrassé du fibrinogène et des facteurs de coagulation",       category: "Biologie" },
  { word: "synapse",       definition: "Zone de contact fonctionnel entre deux neurones ou entre un neurone et son effecteur", category: "Biologie" },
  { word: "toxine",        definition: "Substance toxique élaborée par un organisme vivant",                             category: "Biologie" },
  { word: "triglycerides", definition: "Lipides de réserve circulant dans le sang et stockés dans le tissu adipeux",    category: "Biologie" },
  { word: "virus",         definition: "Agent infectieux à l'intérieur des cellules, composé d'acides nucléiques et d'une capside", category: "Biologie" },
  { word: "acide aminé",   definition: "Molécule organique constituant de base des protéines",                           category: "Biologie" },
  { word: "adrénaline",    definition: "Hormone de stress sécrétée par les glandes surrénales préparant l'organisme à l'action", category: "Biologie" },
  { word: "cytokine",      definition: "Protéine de signalisation cellulaire régulant la réponse immunitaire et l'inflammation", category: "Biologie" },
  { word: "epigenetique",  definition: "Étude des modifications héréditables de l'expression des gènes sans altération de la séquence ADN", category: "Biologie" },
  { word: "homeostasie",   definition: "Tendance de l'organisme à maintenir ses paramètres physiologiques dans des limites stables", category: "Biologie" },
  { word: "phagocytose",   definition: "Processus par lequel une cellule ingère et détruit une particule ou un micro-organisme", category: "Biologie" },
  { word: "proteine",      definition: "Macromolécule biologique constituée d'acides aminés assurant de nombreuses fonctions cellulaires", category: "Biologie" },
  { word: "sterone",       definition: "Lipide à structure en quatre cycles carbonés dont font partie les hormones sexuelles", category: "Biologie" },

  // ── SPÉCIALITÉS MÉDICALES ────────────────────────────────────
  { word: "acupuncture",   definition: "Technique thérapeutique d'origine chinoise utilisant l'insertion d'aiguilles en des points précis du corps", category: "Spécialité" },
  { word: "cardiologie",   definition: "Spécialité médicale dédiée au diagnostic et au traitement des maladies du cœur et des vaisseaux", category: "Spécialité" },
  { word: "chirurgie",     definition: "Intervention médicale manuelle ou instrumentale nécessitant une incision du corps", category: "Spécialité" },
  { word: "dermatologie",  definition: "Branche de la médecine spécialisée dans les maladies de la peau, des ongles et des muqueuses", category: "Spécialité" },
  { word: "echographie",   definition: "Imagerie médicale utilisant des ultrasons pour visualiser les organes en temps réel", category: "Spécialité" },
  { word: "endoscopie",    definition: "Examen visuel de l'intérieur d'une cavité ou d'un organe par un tube optique flexible", category: "Spécialité" },
  { word: "geriatrie",     definition: "Spécialité médicale consacrée aux maladies et aux soins des personnes âgées",       category: "Spécialité" },
  { word: "hematologie",   definition: "Spécialité médicale étudiant le sang, les organes hématopoïétiques et leurs maladies", category: "Spécialité" },
  { word: "kinesitherapie",definition: "Traitement par des exercices physiques, des massages ou des mobilisations pour restaurer les fonctions motrices", category: "Spécialité" },
  { word: "mammographie",  definition: "Examen radiologique des seins pour le dépistage des anomalies, notamment le cancer",  category: "Spécialité" },
  { word: "nephrologie",   definition: "Spécialité médicale consacrée aux maladies des reins et du système urinaire",        category: "Spécialité" },
  { word: "neurologie",    definition: "Branche de la médecine traitant des maladies du système nerveux central et périphérique", category: "Spécialité" },
  { word: "oncologie",     definition: "Spécialité médicale dédiée à l'étude et au traitement des cancers",                 category: "Spécialité" },
  { word: "ophtalmologie", definition: "Spécialité médicale traitant des maladies et des défauts de vision de l'œil",       category: "Spécialité" },
  { word: "orthopedie",    definition: "Spécialité chirurgicale traitant les affections de l'appareil locomoteur",           category: "Spécialité" },
  { word: "pediatrie",     definition: "Branche de la médecine spécialisée dans la santé et les maladies de l'enfant",      category: "Spécialité" },
  { word: "psychiatrie",   definition: "Spécialité médicale dédiée au diagnostic et au traitement des troubles mentaux",     category: "Spécialité" },
  { word: "radiologie",    definition: "Spécialité médicale utilisant diverses formes de rayonnements pour l'imagerie diagnostique", category: "Spécialité" },
  { word: "rhumatologie",  definition: "Spécialité médicale traitant les maladies inflammatoires et dégénératives des articulations", category: "Spécialité" },
  { word: "toxicologie",   definition: "Étude scientifique des poisons, de leurs effets et des antidotes",                  category: "Spécialité" },
  { word: "urologie",      definition: "Spécialité chirurgicale traitant les maladies des voies urinaires et génitales masculines", category: "Spécialité" },
  { word: "angiologie",    definition: "Spécialité médicale dédiée aux maladies des vaisseaux sanguins et lymphatiques",    category: "Spécialité" },
  { word: "endocrinologie",definition: "Spécialité médicale étudiant les glandes endocrines et les hormones",               category: "Spécialité" },
  { word: "gastroenterologie", definition: "Spécialité médicale étudiant et traitant les maladies du tube digestif",       category: "Spécialité" },
  { word: "immunologie",   definition: "Science étudiant le système immunitaire et ses mécanismes de défense contre les agents pathogènes", category: "Spécialité" },
  { word: "infectiologie", definition: "Spécialité médicale consacrée au diagnostic et au traitement des maladies infectieuses", category: "Spécialité" },

  // ── DIAGNOSTICS & EXAMENS ────────────────────────────────────
  { word: "diagnostic",    definition: "Identification d'une maladie d'après les symptômes et les résultats d'examens",    category: "Diagnostic" },
  { word: "electrocardiogramme", definition: "Enregistrement graphique de l'activité électrique du cœur",                category: "Diagnostic" },
  { word: "electroencephalogramme", definition: "Enregistrement de l'activité électrique du cerveau via des électrodes posées sur le crâne", category: "Diagnostic" },
  { word: "scanner",       definition: "Technique d'imagerie médicale utilisant des rayons X pour obtenir des coupes corporelles", category: "Diagnostic" },
  { word: "biopsie",       definition: "Prélèvement d'un fragment de tissu pour analyse anatomopathologique",              category: "Diagnostic" },
  { word: "scintigraphie", definition: "Technique d'imagerie nucléaire explorant le fonctionnement d'un organe après injection d'un traceur radioactif", category: "Diagnostic" },
  { word: "spirometrie",   definition: "Mesure des volumes et des débits d'air lors de la respiration pour évaluer la fonction pulmonaire", category: "Diagnostic" },
  { word: "coloscopie",    definition: "Examen endoscopique permettant l'exploration visuelle du côlon et du rectum",      category: "Diagnostic" },
  { word: "prise de sang", definition: "Prélèvement veineux permettant l'analyse de nombreux paramètres biologiques",     category: "Diagnostic" },

  // ── SANTÉ PUBLIQUE & CONCEPTS ────────────────────────────────
  { word: "epidemie",      definition: "Propagation rapide d'une maladie infectieuse à un grand nombre de personnes dans une région donnée", category: "Santé publique" },
  { word: "infection",     definition: "Envahissement de l'organisme par des micro-organismes pathogènes",                 category: "Santé publique" },
  { word: "inflammation",  definition: "Réaction locale de défense du tissu à une agression physique, chimique ou microbienne", category: "Santé publique" },
  { word: "parasite",      definition: "Organisme vivant aux dépens d'un organisme hôte sans lui apporter de bénéfice",  category: "Santé publique" },
  { word: "prevention",    definition: "Ensemble des mesures visant à éviter l'apparition, le développement ou l'aggravation des maladies", category: "Santé publique" },
  { word: "prothese",      definition: "Dispositif artificiel remplaçant une partie du corps absente ou déficiente",       category: "Santé publique" },
  { word: "quarantaine",   definition: "Isolement préventif de personnes ayant été exposées à une maladie contagieuse",   category: "Santé publique" },
  { word: "remission",     definition: "Atténuation ou disparition temporaire ou durable des symptômes d'une maladie",    category: "Santé publique" },
  { word: "sante",         definition: "État de complet bien-être physique, mental et social selon l'OMS",                 category: "Santé publique" },
  { word: "soins palliatifs",definition: "Soins actifs et complets apportés aux personnes souffrant d'une maladie grave, visant à soulager", category: "Santé publique" },
  { word: "transfusion sanguine", definition: "Transfert de sang ou de composants sanguins d'un donneur à un receveur",  category: "Santé publique" },
  { word: "transplantation",definition: "Greffe d'un organe, d'un tissu ou de cellules prélevés sur un donneur",          category: "Santé publique" },
  { word: "triage",        definition: "Classement des patients selon l'urgence de leur prise en charge médicale",        category: "Santé publique" },
  { word: "xenogreffe",    definition: "Transplantation d'organes ou de tissus entre espèces animales différentes",       category: "Santé publique" },
  { word: "zoonose",       definition: "Maladie infectieuse transmissible naturellement de l'animal à l'homme et vice-versa", category: "Santé publique" },
];

// Exporter pour utilisation dans game.js
// (Compatible avec chargement direct via <script> sans module bundler)
if (typeof module !== 'undefined') module.exports = { WORDS_DATA };
